= 概要
:revdate: 2025-09-16
:page-revdate: {revdate}

== {product-name}

{product-name}は、SUSE Rancher Primeの主要機能であり、オープンソースエンジンlink:https://github.com/rancher/k3k[K3k]の軽量な特性と、SUSE Virtual Cluster Managementのエンタープライズグレードの管理機能を統合しています。

このソリューションは、*Kubernetesにおけるマルチテナンシー*の次世代を実現するように設計されており、プラットフォームチームの管理が容易になり、開発者はセルフサービスでイノベーションを起こすことができます。
{product-name}を使用すると、link:https://k3s.io/[K3s]を使って、フル物理クラスターのプロビジョニングと管理のオーバーヘッドなしに、必要に応じて軽量なKubernetesコントロールプレーンを起動することができます。

これにより、次のことが可能になります：

* 安全で堅牢なマルチテナントワークロードの隔離を実現します。
* 多くの仮想クラスター間でワーカーノードとプラットフォームサービスを共有することにより、インフラストラクチャコストを最適化します。
* 開発者が他の人に影響を与えることなくセルフサービスで実験できるようにします。
* プラットフォームチームにポリシー、ガバナンス、ライフサイクル管理ツールを用いて制御を提供します。

{product-name}は、開発者の自律性とオペレーターの制御の間で適切なバランスを保ち、現代のKubernetesプラットフォームのためのスケーラブルな基盤を作成します。

== 主なコンポーネント

* *SUSE Virtual Cluster Engine*：SUSE Virtual Cluster Engineを支えるオープンソースプロジェクトであるK3kは、CNCF Kubernetes適合テストに合格し、link:https://www.cncf.io/training/certification/software-conformance/[CNCF認定Kubernetes®ソフトウェア適合プログラム]にリストされています。軽量なCNCFプロジェクトであるK3sに基づくK3kは、ワークロードとツールに対して相互運用性、互換性、一貫したKubernetes体験を保証します。

* *SUSE Virtual Cluster Management*：エンタープライズ対応の管理インターフェースを使用して、SUSE Rancher Managerから直接{product-name}を大規模に管理します。
これらには、次の機能があります。
- Rancher統合 - Rancher RBACの利点を享受し、それを拡張します。Rancherから直接仮想クラスターとポリシーを作成および管理します。
- CAPIプロバイダー - ライフサイクル自動化のためのクラスターAPIサポート。
- Terraformプロバイダー（プレリリース） - クラスター管理をスケールし標準化するためのInfrastructure as Codeワークフロー。

== なぜ{product-name}ですか？

{product-name}を使用することで、組織は次のことができます：

* 共有モードと仮想モードの2つのモードで真のKubernetesマルチテナンシーを提供し、ほとんどの本番使用ケースに適合します（ドキュメントリンク - モードの選択方法）。
* ホストから仮想クラスターへの共有ワーカープールと共有サービスを通じて、クラウドおよびインフラストラクチャコストを削減します（ドキュメントリンク - 共有モード）。
* 自己サービスモードで迅速かつ軽量なクラスターを使用して、開発者のワークフローを加速します（ドキュメントリンク - クイックスタートUI）。
* ポリシー、ガバナンス、ライフサイクルツールを使用してガードレールを定義し、プラットフォームと開発者チーム間のシームレスなコラボレーションを可能にします（ドキュメントリンク - 仮想クラスターのポリシー）。

**認証の詳細*：K3kの適合性結果は、link:https://www.cncf.io/training/certification/software-conformance/[CNCF掲載ページ]に公開されています。

Kubernetes®は、アメリカ合衆国および他の国におけるLinux Foundationの登録商標であり、Linux Foundationからのライセンスに基づいて使用されています。