= クイックスタート
:revdate: 2025-11-19
:page-revdate: {revdate}

ifndef::ss-build-community[]
クラスターのインストールと作成については、link:https://scc.suse.com/rancher-docs/rancherprime/latest/en/suse-virtual-cluster/installation-and-upgrades/quickstart.html[UIを介したインストールとクラスターの作成]を参照してください。
endif::[]

ifdef::ss-build-community[]
K3k、Kubernetes in Kubernetesは、既存のKubernetes環境内で孤立したK3sクラスターを作成および管理するためのツールです。これにより、マルチテナンシー、実験、およびリソースの分離が可能になり、同じ物理ホスト上で複数の軽量Kubernetesクラスターを実行することでインフラストラクチャコストを削減します。K3kは、リソースの利用効率を最適化する「共有」モードと、専用のK3sサーバーポッドによる完全な分離を提供する「仮想」モードの両方を提供します。これにより、別々の物理リソースを管理するオーバーヘッドなしで、完全なKubernetes体験にアクセスできます。

K3kは、組み込みクラスターの管理を簡素化するためにRancherと統合されています。

== インストール

このセクションでは、K3kおよびk3kcliのインストール手順を提供します。

=== 前提条件

* https://helm.sh/[Helm]をインストールする必要があります。始めるには、 https://helm.sh/docs/[Helmのドキュメント]を参照してください。
* 既存の https://documentation.suse.com/cloudnative/rke2/latest/en/install/quickstart.html[RKE2] Kubernetesクラスター（推奨）。
* デフォルトのストレージクラスを持つ構成済みのストレージプロバイダー。

NOTE: ストレージプロバイダーがない場合、クラスターを一時的または静的ストレージを使用するように構成できます。これらのオプションの使用方法については、xref:advanced-usage.adoc#_using_the_cli[k3kcliの高度な使用法]を参照してください。

=== K3kコントローラーをインストールします。

NOTE: Rancher Primeの顧客は、 https://scc.suse.com/rancher-docs/rancherprime/latest/en/suse-virtual-cluster/installation-and-upgrades/quickstart.html[クイックスタート]を参照してください。

. K3k Helmリポジトリを追加します：
+
[,bash]
----
helm repo add k3k https://rancher.github.io/k3k
helm repo update
----

. K3kコントローラーをインストールします：
+
[,bash]
----
helm install --namespace k3k-system --create-namespace k3k k3k/k3k
----

=== `k3kcli`をインストールします。

`k3kcli`は、K3kクラスターを迅速かつ簡単に作成し、自動的にkubeconfigを介して公開する方法を提供します。

これをインストールするには、GitHubリリースページからアーキテクチャに適した最新のバージョンをダウンロードしてください。

例えば、Linux amd64 バージョンを次のようにダウンロードできます：

[subs="+attributes",bash]
----
wget -qO k3kcli https://github.com/rancher/k3k/releases/download/{k3k-latest-version}/k3kcli-linux-amd64 && \
  chmod +x k3kcli && \
  sudo mv k3kcli /usr/local/bin
----

次に、次のコマンドを実行します：

[,bash]
----
k3kcli --version
k3kcli version v1.0.0
----

== 使用方法

このセクションでは、`k3kcli` を使用して K3k クラスターを管理する方法の例を提供します。

`K3k` は、現在設定されている kubectl コンテキストの範囲内で動作します。これは、K3k が `--kubeconfig` フラグ、$KUBECONFIG 環境変数、およびデフォルトの $HOME/.kube/config ファイルを含む、コンテキスト設定の標準 Kubernetes メカニズムを尊重することを意味します。作成する K3k クラスターは、kubectl が現在指している Kubernetes クラスター内に存在します。

=== K3k クラスターの作成

新しい K3k クラスターを作成するには、次のコマンドを使用します：

[,bash]
----
k3kcli cluster create mycluster
----

[NOTE]
====
*Rancher 管理ホストクラスター上に K3k クラスターを作成する*

ホスト Kubernetes クラスターが Rancher によって管理されている場合（たとえば、kubeconfig のサーバーアドレスに Rancher の URL が含まれている場合）、K3k クラスターを作成する際に `--kubeconfig-server` フラグを使用します：

[,bash]
----
k3kcli cluster create --kubeconfig-server <host_node_IP_or_load_balancer_IP> mycluster
----

これにより、生成された kubeconfig が正しいエンドポイントに接続されることが保証されます。
====

K3s サーバーが準備完了になると、`k3kcli` が必要な kubeconfig ファイルを生成し、それを使用する方法についての指示を表示します。

出力の一例を次に示します：

[,yaml]
----
INFO[0000] Creating a new cluster [mycluster]
INFO[0000] Extracting Kubeconfig for [mycluster] cluster 
INFO[0000] waiting for cluster to be available..
INFO[0073] certificate CN=system:admin,O=system:masters signed by CN=k3s-client-ca@1738746570: notBefore=2025-02-05 09:09:30 +0000 UTC notAfter=2026-02-05 09:10:42 +0000 UTC 
INFO[0073] You can start using the cluster with: 

        export KUBECONFIG=/my/current/directory/mycluster-kubeconfig.yaml
        kubectl cluster-info
----

生成された kubeconfig をエクスポートした後、Kubernetes クラスターにアクセスできます：

[,bash]
----
export KUBECONFIG=/my/current/directory/mycluster-kubeconfig.yaml
kubectl get nodes
kubectl get pods -A
----

特定のネームスペースに直接クラスターリソースを作成して K3k クラスターを作成することもできます：

[,bash]
----
kubectl apply -f - <<EOF
apiVersion: k3k.io/v1beta1
kind: Cluster
metadata:
  name: mycluster
  namespace: k3k-mycluster
EOF
----

そして、`k3kcli` を使用して kubeconfig を取得します：

[,bash]
----
k3kcli kubeconfig generate --namespace k3k-mycluster --name mycluster 
----

=== K3k クラスターの削除

K3k クラスターを削除するには、次のコマンドを使用します：

[,bash]
----
k3kcli cluster delete mycluster
----
endif::[]
