= 快速入门
:revdate: 2025-11-19
:page-revdate: {revdate}

ifndef::ss-build-community[]
要了解有关安装和创建集群的信息，请参见link:https://scc.suse.com/rancher-docs/rancherprime/latest/en/suse-virtual-cluster/installation-and-upgrades/quickstart.html[通过 UI 进行安装和集群创建]。
endif::[]

ifdef::ss-build-community[]
K3k，即 Kubernetes 中的 Kubernetes，是一个工具，使您能够在现有的 Kubernetes 环境中创建和管理隔离的 K3s 集群。它支持多租户、实验和资源隔离，通过允许您在同一物理主机上运行多个轻量级 Kubernetes 集群，从而降低基础设施成本。K3k 提供 "共享" 模式，优化资源利用率，以及 "虚拟" 模式，提供与专用 K3s 服务器 Pod 完全隔离的环境。这使您能够在不管理单独物理资源的情况下，访问完整的 Kubernetes 体验。

K3k 与 Rancher 集成，以简化对嵌入式集群的管理。

== 安装

本节提供有关如何安装 K3k 和 k3kcli 的说明。

=== 先决条件

* 必须安装 https://helm.sh/[Helm]才能使用这些图表。请参考 https://helm.sh/docs/[Helm 的文档]以开始使用。
* 一个现有的 https://documentation.suse.com/cloudnative/rke2/latest/en/install/quickstart.html[RKE2] Kubernetes 集群（推荐）。
* 一个配置好的存储提供者，带有默认存储类。

NOTE: 如果您没有存储提供者，可以将集群配置为使用临时或静态存储。请查阅xref:advanced-usage.adoc#_using_the_cli[k3kcli 高级用法]以获取使用这些选项的说明。

=== 安装 K3k 控制器

NOTE: Rancher Prime 客户，请参见 https://scc.suse.com/rancher-docs/rancherprime/latest/en/suse-virtual-cluster/installation-and-upgrades/quickstart.html[快速入门]。

. 添加 K3k Helm 储存库：
+
[,bash]
----
helm repo add k3k https://rancher.github.io/k3k
helm repo update
----

. 安装 K3k 控制器：
+
[,bash]
----
helm install --namespace k3k-system --create-namespace k3k k3k/k3k
----

=== 安装`k3kcli`

`k3kcli` 提供了一种快速简便的方法来创建 K3k 集群，并通过 kubeconfig 自动暴露它们。

要安装它，只需从 GitHub Releases 页面下载适合您架构的最新可用版本。

例如，您可以下载 Linux amd64 版本，命令为：

[subs="+attributes",bash]
----
wget -qO k3kcli https://github.com/rancher/k3k/releases/download/{k3k-latest-version}/k3kcli-linux-amd64 && \
  chmod +x k3kcli && \
  sudo mv k3kcli /usr/local/bin
----

现在运行：

[,bash]
----
k3kcli --version
k3kcli version v1.0.0
----

== 用法

本节提供了如何使用 `k3kcli` 来管理您的 K3k 集群的示例。

`K3k` 在您当前配置的 kubectl 上下文中运行。这意味着 K3k 遵循标准 Kubernetes 上下文配置机制，包括 `--kubeconfig` 标志、$KUBECONFIG 环境变量和默认的 $HOME/.kube/config 文件。您创建的任何 K3k 集群将位于 kubectl 当前指向的 Kubernetes 集群内。

=== 创建 K3k 集群

要创建一个新的 K3k 集群，请使用以下命令：

[,bash]
----
k3kcli cluster create mycluster
----

[NOTE]
====
*在 Rancher 管理的主机集群上创建 K3k 集群*

如果您的主机 Kubernetes 集群由 Rancher 管理（例如，您的 kubeconfig 的服务器地址包含 Rancher URL），请在创建 K3k 集群时使用 `--kubeconfig-server` 标志：

[,bash]
----
k3kcli cluster create --kubeconfig-server <host_node_IP_or_load_balancer_IP> mycluster
----

这确保生成的 kubeconfig 连接到正确的端点。
====

当 K3s 服务器准备就绪时，`k3kcli` 将生成必要的 kubeconfig 文件并打印使用说明。

下面是一个输出示例：

[,yaml]
----
INFO[0000] Creating a new cluster [mycluster]
INFO[0000] Extracting Kubeconfig for [mycluster] cluster 
INFO[0000] waiting for cluster to be available..
INFO[0073] certificate CN=system:admin,O=system:masters signed by CN=k3s-client-ca@1738746570: notBefore=2025-02-05 09:09:30 +0000 UTC notAfter=2026-02-05 09:10:42 +0000 UTC 
INFO[0073] You can start using the cluster with: 

        export KUBECONFIG=/my/current/directory/mycluster-kubeconfig.yaml
        kubectl cluster-info
----

导出生成的 kubeconfig 后，您可以访问您的 Kubernetes 集群：

[,bash]
----
export KUBECONFIG=/my/current/directory/mycluster-kubeconfig.yaml
kubectl get nodes
kubectl get pods -A
----

您还可以直接在某个名称空间中创建一个 Cluster 资源，以创建 K3k 集群：

[,bash]
----
kubectl apply -f - <<EOF
apiVersion: k3k.io/v1beta1
kind: Cluster
metadata:
  name: mycluster
  namespace: k3k-mycluster
EOF
----

并使用 `k3kcli` 来检索 kubeconfig：

[,bash]
----
k3kcli kubeconfig generate --namespace k3k-mycluster --name mycluster 
----

=== 删除 K3k 集群

要删除 K3k 集群，请使用以下命令：

[,bash]
----
k3kcli cluster delete mycluster
----
endif::[]
