= Inicio rápido
:revdate: 2025-11-19
:page-revdate: {revdate}

ifndef::ss-build-community[]
Para saber sobre la instalación y creación de los clústeres, consulte link:https://scc.suse.com/rancher-docs/rancherprime/latest/en/suse-virtual-cluster/installation-and-upgrades/quickstart.html[Instalación y creación de clústeres a través de la interfaz de usuario].
endif::[]

ifdef::ss-build-community[]
K3k, Kubernetes en Kubernetes, es una herramienta que te permite crear y gestionar clústeres K3s aislados dentro de tu entorno Kubernetes existente. Permite la multi-tenencia, la experimentación y el aislamiento de recursos, reduciendo los costos de infraestructura al permitirte ejecutar múltiples clústeres de Kubernetes ligeros en el mismo host físico. K3k ofrece tanto el modo "compartido", optimizando la utilización de recursos, como el modo "virtual", proporcionando un aislamiento completo con pods de servidor K3s dedicados. Esto te permite acceder a una experiencia completa de Kubernetes sin la sobrecarga de gestionar recursos físicos separados.

K3k se integra con Rancher para una gestión simplificada de tus clústeres integrados.

== Instalación

Esta sección proporciona instrucciones sobre cómo instalar K3k y el k3kcli.

=== Requisitos previos

* https://helm.sh/[Helm] debe estar instalado para usar los charts. Por favor, consulta https://helm.sh/docs/[la documentación de Helm] para comenzar.
* Un clúster de Kubernetes https://documentation.suse.com/cloudnative/rke2/latest/en/install/quickstart.html[RKE2] existente (recomendado).
* Un proveedor de almacenamiento configurado con una clase de almacenamiento predeterminada.

NOTE: Si no tienes un proveedor de almacenamiento, puedes configurar el clúster para usar almacenamiento efímero o estático. Por favor, consulta el xref:advanced-usage.adoc#_using_the_cli[Uso avanzado de k3kcli] para instrucciones sobre cómo usar estas opciones.

=== Instala el controlador K3k

NOTE: Clientes de Rancher Prime, por favor vean https://scc.suse.com/rancher-docs/rancherprime/latest/en/suse-virtual-cluster/installation-and-upgrades/quickstart.html[Inicio rápido].

. Añade el repositorio de Helm de K3k:
+
[,bash]
----
helm repo add k3k https://rancher.github.io/k3k
helm repo update
----

. Instala el controlador K3k:
+
[,bash]
----
helm install --namespace k3k-system --create-namespace k3k k3k/k3k
----

=== Instala el `k3kcli`

El `k3kcli` proporciona una forma rápida y fácil de crear clústeres K3k y los expone automáticamente a través de un kubeconfig.

Para instalarlo, simplemente descarga la última versión disponible para tu arquitectura desde la página de lanzamientos de GitHub.

Por ejemplo, puedes descargar la versión amd64 de Linux con:

[subs="+attributes",bash]
----
wget -qO k3kcli https://github.com/rancher/k3k/releases/download/{k3k-latest-version}/k3kcli-linux-amd64 && \
  chmod +x k3kcli && \
  sudo mv k3kcli /usr/local/bin
----

Ahora ejecuta:

[,bash]
----
k3kcli --version
k3kcli version v1.0.0
----

== Uso

Esta sección proporciona ejemplos de cómo utilizar el `k3kcli` para gestionar tus clústeres K3k.

`K3k` opera dentro del contexto de kubectl configurado actualmente. Esto significa que K3k respeta los mecanismos estándar de Kubernetes para la configuración de contextos, incluyendo la bandera `--kubeconfig`, la variable de entorno $KUBECONFIG y el archivo por defecto $HOME/.kube/config. Cualquier clúster K3k que crees residirá dentro del clúster de Kubernetes al que tu kubectl está apuntando actualmente.

=== Creando un Clúster K3k

Para crear un nuevo clúster K3k, utiliza el siguiente comando:

[,bash]
----
k3kcli cluster create mycluster
----

[NOTE]
====
*Creando un Clúster K3k en un Clúster de Host Gestionado por Rancher*

Si tu clúster de Kubernetes de host es gestionado por Rancher (por ejemplo, la dirección del servidor de tu kubeconfig incluye una URL de Rancher), utiliza la bandera `--kubeconfig-server` al crear tu clúster K3k:

[,bash]
----
k3kcli cluster create --kubeconfig-server <host_node_IP_or_load_balancer_IP> mycluster
----

Esto asegura que el kubeconfig generado se conecte al endpoint correcto.
====

Cuando el servidor K3s esté listo, `k3kcli` generará el archivo kubeconfig necesario e imprimirá instrucciones sobre cómo utilizarlo.

Aquí tienes un ejemplo de la salida:

[,yaml]
----
INFO[0000] Creating a new cluster [mycluster]
INFO[0000] Extracting Kubeconfig for [mycluster] cluster 
INFO[0000] waiting for cluster to be available..
INFO[0073] certificate CN=system:admin,O=system:masters signed by CN=k3s-client-ca@1738746570: notBefore=2025-02-05 09:09:30 +0000 UTC notAfter=2026-02-05 09:10:42 +0000 UTC 
INFO[0073] You can start using the cluster with: 

        export KUBECONFIG=/my/current/directory/mycluster-kubeconfig.yaml
        kubectl cluster-info
----

Después de exportar el kubeconfig generado, puedes acceder a tu clúster de Kubernetes:

[,bash]
----
export KUBECONFIG=/my/current/directory/mycluster-kubeconfig.yaml
kubectl get nodes
kubectl get pods -A
----

También puedes crear directamente un recurso de Clúster en un espacio de nombres determinado, para crear un clúster K3k:

[,bash]
----
kubectl apply -f - <<EOF
apiVersion: k3k.io/v1beta1
kind: Cluster
metadata:
  name: mycluster
  namespace: k3k-mycluster
EOF
----

y utilizar el `k3kcli` para recuperar el kubeconfig:

[,bash]
----
k3kcli kubeconfig generate --namespace k3k-mycluster --name mycluster 
----

=== Eliminando un Clúster K3k

Para eliminar un clúster K3k, utiliza el siguiente comando:

[,bash]
----
k3kcli cluster delete mycluster
----
endif::[]
